project_name: gnmi-server-gen
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.versionNum={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -X main.gitURL={{.GitURL}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    hooks:
      post: upx "{{ .Path }}"
dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - gnmi-server-gen
    image_templates:
      - "ghcr.io/karimra/gnmi-server-gen:latest"
      - 'ghcr.io/karimra/gnmi-server-gen:{{ replace .Version "v" ""}}'
    dockerfile: goreleaser.dockerfile
    skip_push: false
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
      386: i386
      arm: armv7
      arm64: aarch64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: gnmi-server-gen
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: x86_64
      386: i386
      darwin: Darwin
      linux: Linux
    vendor: gnmi-server-gen
    maintainer: Karim Radhouani <medkarimrdi@gmail.com>
    description: gNMI server traffic generator
    license: Apache 2.0
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin